print ("Question 1")
print ("what is 9X4")
print ("Question 2")
print ("what is 8X6")
print ("Question 3")
print ("what is 7X3") 
print ("Question 4")
print ("what is 5X5")
print ("Question 5")
print ("what is 6X8")
print ("Question 6")
print ("what is 4X7")
print ("Want to play again")